package com.biu.wiki.mapper;

import com.biu.wiki.domain.Ebook;
import java.util.List;

public interface EbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Tue Mar 08 13:54:38 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Tue Mar 08 13:54:38 CST 2022
     */
    int insert(Ebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Tue Mar 08 13:54:38 CST 2022
     */
    Ebook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Tue Mar 08 13:54:38 CST 2022
     */
    List<Ebook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated Tue Mar 08 13:54:38 CST 2022
     */
    int updateByPrimaryKey(Ebook record);
}